"""Quality-profile defaults (extracted from converter.py).

Pure configuration: learning rates, loss weights, schedules, and refinement
knobs per profile. PNG2SVGConverter resolves these at construction.
"""

from __future__ import annotations

from typing import Any, Dict


def get_profile_defaults(profile: str) -> Dict[str, Dict[str, Any]]:
    """Return tuned defaults for quality profile."""
    profiles: Dict[str, Dict[str, Dict[str, Any]]] = {
        "m4-fast-loop": {
            "learning_rates": {
                "position": 0.0095,
                "scale": 0.0040,
                "theta": 0.0040,
                "color": 0.016,
                "alpha": 0.0080,
            },
            "loss_weights": {"l1_weight": 1.0, "ssim_weight": 0.18},
            "refinement": {
                "densify_percentile": 90.0,
                "densify_fraction": 0.18,
                "base_layer_fraction": 0.45,
                "base_layer_alpha": 0.34,
                "sigma_min": 1.4,
                "sigma_max": 4.0,
                "sigma_scale": 2.2,
                "sigma_minor_min": 0.45,
                "coverage_sigma_max": 5.5,
                "coverage_alpha_fill": 0.32,
                "coverage_threshold": 0.035,
                "coverage_target": 0.92,
                "coverage_footprint_sigma": 3.0,
                "coverage_densify_boost": 1.2,
                "reallocate_for_coverage_fraction": 0.04,
                "densify_weight_error": 0.60,
                "densify_weight_uncovered": 0.30,
                "densify_weight_edge": 0.10,
                "alpha_base": 0.30,
                "alpha_scale": 0.40,
                "alpha_min": 0.20,
                "alpha_max": 0.85,
                "prune_weight_contribution": 0.75,
                "prune_weight_residual": 0.25,
                "prune_weight_uncovered": 0.10,
                "prune_sample_radius": 1.3,
                "residual_color_gain": 0.60,
                "final_fill_fraction": 0.06,
                "structure_precompute_enabled": True,
                "structure_smoothing_sigma": 0.0,
                "structure_anisotropy_clip": 10.0,
                "structure_min_coherence": 0.12,
                "structure_local_window": 7,
                "local_structure_anisotropy_clip": 4.0,
                "local_structure_min_coherence": 0.12,
                "local_structure_min_energy": 1e-4,
                "init_anisotropy_threshold": 1.55,
                "densify_anisotropy_threshold": 1.30,
                "densify_anisotropy_edge_threshold": 0.14,
                "densify_strong_edge_threshold": 0.38,
                "residual_detail_enabled": False,
                "residual_detail_reserve_fraction": 0.00,
                "residual_detail_passes": 1,
                "residual_detail_percentile": 90.0,
                "residual_detail_fraction": 0.10,
                "residual_detail_sigma_min": 0.35,
                "residual_detail_sigma_max": 1.40,
                "residual_detail_alpha_min": 0.14,
                "residual_detail_alpha_max": 0.65,
                "residual_detail_iters": 4,
                "residual_detail_edge_weight": 0.25,
                "residual_detail_color_gain": 0.90,
            },
            "schedule": {
                "enabled": True,
                "check_interval": 25,
                "patience_checks": 1,
                "decay_ratio": 2.0,
                "max_decays": 1,
                "min_delta": 4e-4,
            },
        },
        "fast": {
            "learning_rates": {
                "position": 0.009,
                "scale": 0.004,
                "theta": 0.004,
                "color": 0.016,
                "alpha": 0.008,
            },
            "loss_weights": {"l1_weight": 1.0, "ssim_weight": 0.18},
            "refinement": {
                "densify_percentile": 90.0,
                "densify_fraction": 0.18,
                "base_layer_fraction": 0.45,
                "base_layer_alpha": 0.34,
                "sigma_min": 1.4,
                "sigma_max": 4.0,
                "sigma_scale": 2.2,
                "sigma_minor_min": 0.45,
                "coverage_sigma_max": 5.5,
                "coverage_alpha_fill": 0.32,
                "coverage_threshold": 0.035,
                "coverage_target": 0.92,
                "coverage_footprint_sigma": 3.0,
                "coverage_densify_boost": 1.2,
                "reallocate_for_coverage_fraction": 0.04,
                "densify_weight_error": 0.60,
                "densify_weight_uncovered": 0.30,
                "densify_weight_edge": 0.10,
                "alpha_base": 0.30,
                "alpha_scale": 0.40,
                "alpha_min": 0.20,
                "alpha_max": 0.85,
                "prune_weight_contribution": 0.75,
                "prune_weight_residual": 0.25,
                "prune_weight_uncovered": 0.10,
                "prune_sample_radius": 1.3,
                "residual_color_gain": 0.60,
                "final_fill_fraction": 0.06,
                "structure_precompute_enabled": False,
                "structure_smoothing_sigma": 0.0,
                "structure_anisotropy_clip": 10.0,
                "structure_min_coherence": 0.12,
                "structure_local_window": 7,
                "local_structure_anisotropy_clip": 4.0,
                "local_structure_min_coherence": 0.12,
                "local_structure_min_energy": 1e-4,
                "init_anisotropy_threshold": 1.55,
                "densify_anisotropy_threshold": 1.30,
                "densify_anisotropy_edge_threshold": 0.14,
                "densify_strong_edge_threshold": 0.38,
                "residual_detail_enabled": False,
                "residual_detail_reserve_fraction": 0.00,
                "residual_detail_passes": 1,
                "residual_detail_percentile": 90.0,
                "residual_detail_fraction": 0.10,
                "residual_detail_sigma_min": 0.35,
                "residual_detail_sigma_max": 1.40,
                "residual_detail_alpha_min": 0.14,
                "residual_detail_alpha_max": 0.65,
                "residual_detail_iters": 4,
                "residual_detail_edge_weight": 0.25,
                "residual_detail_color_gain": 0.90,
            },
            "schedule": {
                "enabled": True,
                "check_interval": 50,
                "patience_checks": 2,
                "decay_ratio": 2.0,
                "max_decays": 1,
                "min_delta": 2e-4,
            },
        },
        "balanced": {
            "learning_rates": {
                "position": 0.01,
                "scale": 0.005,
                "theta": 0.005,
                "color": 0.02,
                "alpha": 0.01,
            },
            "loss_weights": {"l1_weight": 1.0, "ssim_weight": 0.2},
            "refinement": {
                "densify_percentile": 85.0,
                "densify_fraction": 0.25,
                "base_layer_fraction": 0.40,
                "base_layer_alpha": 0.40,
                "sigma_min": 1.25,
                "sigma_max": 4.0,
                "sigma_scale": 2.5,
                "sigma_minor_min": 0.40,
                "coverage_sigma_max": 6.5,
                "coverage_alpha_fill": 0.36,
                "coverage_threshold": 0.03,
                "coverage_target": 0.965,
                "coverage_footprint_sigma": 3.0,
                "coverage_densify_boost": 1.8,
                "reallocate_for_coverage_fraction": 0.06,
                "densify_weight_error": 0.50,
                "densify_weight_uncovered": 0.40,
                "densify_weight_edge": 0.10,
                "alpha_base": 0.35,
                "alpha_scale": 0.45,
                "alpha_min": 0.20,
                "alpha_max": 0.90,
                "prune_weight_contribution": 0.65,
                "prune_weight_residual": 0.35,
                "prune_weight_uncovered": 0.20,
                "prune_sample_radius": 1.4,
                "residual_color_gain": 0.75,
                "final_fill_fraction": 0.09,
                "structure_precompute_enabled": False,
                "structure_smoothing_sigma": 0.0,
                "structure_anisotropy_clip": 10.0,
                "structure_min_coherence": 0.12,
                "structure_local_window": 7,
                "local_structure_anisotropy_clip": 4.0,
                "local_structure_min_coherence": 0.12,
                "local_structure_min_energy": 1e-4,
                "init_anisotropy_threshold": 1.55,
                "densify_anisotropy_threshold": 1.30,
                "densify_anisotropy_edge_threshold": 0.14,
                "densify_strong_edge_threshold": 0.38,
                "residual_detail_enabled": False,
                "residual_detail_reserve_fraction": 0.00,
                "residual_detail_passes": 1,
                "residual_detail_percentile": 90.0,
                "residual_detail_fraction": 0.10,
                "residual_detail_sigma_min": 0.35,
                "residual_detail_sigma_max": 1.30,
                "residual_detail_alpha_min": 0.14,
                "residual_detail_alpha_max": 0.68,
                "residual_detail_iters": 6,
                "residual_detail_edge_weight": 0.28,
                "residual_detail_color_gain": 0.92,
            },
            "schedule": {
                "enabled": True,
                "check_interval": 50,
                "patience_checks": 3,
                "decay_ratio": 2.0,
                "max_decays": 2,
                "min_delta": 1e-4,
            },
        },
        "max-fidelity": {
            "learning_rates": {
                "position": 0.0075,
                "scale": 0.0055,
                "theta": 0.0055,
                "color": 0.016,
                "alpha": 0.010,
            },
            "loss_weights": {
                "l1_weight": 1.0,
                "ssim_weight": 0.24,
                "gradient_weight": 0.08,
            },
            "refinement": {
                "densify_percentile": 74.0,
                "densify_fraction": 0.40,
                "base_layer_fraction": 0.32,
                "base_layer_alpha": 0.44,
                "sigma_min": 0.45,
                "sigma_max": 3.0,
                "sigma_scale": 2.1,
                "sigma_minor_min": 0.30,
                "coverage_sigma_max": 11.0,
                "coverage_alpha_fill": 0.50,
                "coverage_threshold": 0.025,
                "coverage_target": 0.985,
                "coverage_footprint_sigma": 3.2,
                "coverage_densify_boost": 2.4,
                "reallocate_for_coverage_fraction": 0.10,
                "densify_weight_error": 0.35,
                "densify_weight_uncovered": 0.55,
                "densify_weight_edge": 0.10,
                "alpha_base": 0.22,
                "alpha_scale": 0.62,
                "alpha_min": 0.10,
                "alpha_max": 0.92,
                "prune_weight_contribution": 0.35,
                "prune_weight_residual": 0.65,
                "prune_weight_uncovered": 0.45,
                "prune_sample_radius": 1.5,
                "residual_color_gain": 1.00,
                "final_fill_fraction": 0.12,
                "edge_init_fraction": 0.30,
                "edge_init_percentile": 68.0,
                "edge_init_sigma_min": 0.45,
                "edge_init_sigma_max": 1.25,
                "edge_init_sigma_major_scale": 2.20,
                "edge_init_sigma_major_max": 3.00,
                "edge_init_alpha_min": 0.30,
                "edge_init_alpha_max": 0.72,
                "edge_init_saliency_weight": 0.70,
                "edge_init_anisotropy_threshold": 1.15,
                "structure_precompute_enabled": False,
                "structure_smoothing_sigma": 0.0,
                "structure_anisotropy_clip": 10.0,
                "structure_min_coherence": 0.12,
                "structure_local_window": 7,
                "local_structure_anisotropy_clip": 3.6,
                "local_structure_min_coherence": 0.14,
                "local_structure_min_energy": 1e-4,
                "init_anisotropy_threshold": 1.60,
                "densify_anisotropy_threshold": 1.35,
                "densify_anisotropy_edge_threshold": 0.16,
                "densify_strong_edge_threshold": 0.42,
                "residual_detail_enabled": True,
                "residual_detail_reserve_fraction": 0.08,
                "residual_detail_passes": 1,
                "residual_detail_percentile": 90.0,
                "residual_detail_fraction": 0.18,
                "residual_detail_sigma_min": 0.28,
                "residual_detail_sigma_max": 1.20,
                "residual_detail_alpha_min": 0.16,
                "residual_detail_alpha_max": 0.72,
                "residual_detail_iters": 8,
                "residual_detail_edge_weight": 0.30,
                "residual_detail_edge_fraction": 0.45,
                "residual_detail_edge_percentile": 76.0,
                "residual_detail_edge_gamma": 0.70,
                "residual_detail_edge_error_floor": 0.20,
                "residual_detail_edge_sigma_min": 0.10,
                "residual_detail_edge_sigma_max": 0.70,
                "residual_detail_edge_sigma_major_max": 1.25,
                "residual_detail_edge_alpha_boost": 0.06,
                "residual_detail_edge_color_gain": 1.00,
                "residual_detail_edge_saliency_weight": 0.85,
                "residual_detail_edge_make_threshold": 0.20,
                "residual_detail_edge_anisotropic": True,
                "residual_detail_edge_anisotropy_threshold": 1.20,
                "residual_detail_edge_aspect": 2.00,
                "residual_detail_color_gain": 0.95,
                "region_weighting_enabled": True,
                "region_weight_base": 0.70,
                "region_weight_background": 0.25,
                "region_weight_foreground": 1.00,
                "region_weight_edge": 1.00,
            },
            "schedule": {
                "enabled": True,
                "check_interval": 50,
                "patience_checks": 3,
                "decay_ratio": 1.6,
                "max_decays": 3,
                "min_delta": 5e-5,
            },
        },
    }
    if profile not in profiles:
        raise ValueError(f"Unknown quality profile: {profile}")
    return profiles[profile]
