"""Time-budget presets for content-aware training schedules.

Extracted from converter.py: pure data tables consumed by
PNG2SVGConverter._apply_time_budget_plan.
"""

from __future__ import annotations

from typing import Any, Dict

TIME_BUDGET_ALIASES = {
    "smoke": "1m",
    "1min": "1m",
    "1minute": "1m",
    "5min": "5m",
    "5minute": "5m",
    "10min": "10m",
    "10minute": "10m",
    "20min": "20m",
    "20minute": "20m",
    "30min": "30m",
    "30minute": "30m",
    "photo10k": "photo-native-10k",
    "native10k": "photo-native-10k",
    "native-10k": "photo-native-10k",
    "photo-10k": "photo-native-10k",
    "photo20k": "photo-native-20k",
    "native20k": "photo-native-20k",
    "native-20k": "photo-native-20k",
    "photo-20k": "photo-native-20k",
}

TIME_BUDGET_PRESETS: Dict[str, Dict[str, Any]] = {
    # Budget presets are calibrated for the CPU/Apple-Silicon path by using the
    # native 1500x1000 photo run as the high-end anchor. They are still heuristic:
    # actual runtime depends on backend, image content, and memory pressure.
    "1m": {
        "label": "1m smoke",
        "target_seconds": 60.0,
        "stages": [2],
        "splats_per_megapixel": 340.0,
        "min_splats": 96,
        "max_splats": 512,
        "coverage_sigma_cap_multiplier": 1.00,
        "refinement_overrides": {
            "base_layer_fraction": 0.80,
            "base_layer_alpha": 0.54,
            "saliency_init_fraction": 0.18,
            "saliency_random_fraction": 0.15,
            "densify_weight_saliency": 0.25,
            "residual_detail_saliency_weight": 0.35,
            "region_weight_saliency_boost": 0.35,
            "saliency_sampling_gamma": 0.85,
        },
        "residual_detail_enabled": False,
        "residual_detail_reserve_fraction": 0.0,
        "residual_detail_passes": 0,
        "residual_detail_iters": 0,
    },
    "5m": {
        "label": "5m",
        "target_seconds": 300.0,
        "stages": [18, 12, 6],
        "splats_per_megapixel": 900.0,
        "min_splats": 256,
        "max_splats": 1400,
        "coverage_sigma_cap_multiplier": 0.90,
        "refinement_overrides": {
            "base_layer_fraction": 0.60,
            "base_layer_alpha": 0.48,
            "saliency_init_fraction": 0.30,
            "saliency_random_fraction": 0.30,
            "densify_weight_saliency": 0.45,
            "residual_detail_saliency_weight": 0.55,
            "region_weight_saliency_boost": 0.50,
            "saliency_sampling_gamma": 0.80,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.04,
        "residual_detail_passes": 1,
        "residual_detail_iters": 2,
    },
    "10m": {
        "label": "10m",
        "target_seconds": 600.0,
        "stages": [30, 20, 10],
        "splats_per_megapixel": 1350.0,
        "min_splats": 512,
        "max_splats": 2000,
        "coverage_sigma_cap_multiplier": 0.80,
        "refinement_overrides": {
            "base_layer_fraction": 0.48,
            "base_layer_alpha": 0.44,
            "saliency_init_fraction": 0.38,
            "saliency_random_fraction": 0.42,
            "densify_weight_saliency": 0.65,
            "residual_detail_saliency_weight": 0.75,
            "region_weight_saliency_boost": 0.65,
            "saliency_sampling_gamma": 0.75,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.06,
        "residual_detail_passes": 1,
        "residual_detail_iters": 4,
    },
    "20m": {
        "label": "20m",
        "target_seconds": 1200.0,
        "stages": [32, 12],
        "splats_per_megapixel": 1900.0,
        "min_splats": 640,
        "max_splats": 3200,
        "coverage_sigma_cap_multiplier": 0.74,
        "refinement_overrides": {
            "base_layer_fraction": 0.32,
            "base_layer_alpha": 0.43,
            "initial_splat_fraction": 0.72,
            "initial_splat_cap": 2400,
            "edge_init_fraction": 0.60,
            "edge_init_percentile": 64.0,
            "edge_init_sigma_min": 0.42,
            "edge_init_sigma_max": 1.15,
            "edge_init_sigma_major_scale": 2.50,
            "edge_init_sigma_major_max": 3.00,
            "edge_init_alpha_min": 0.34,
            "edge_init_alpha_max": 0.78,
            "edge_init_saliency_weight": 0.90,
            "saliency_init_fraction": 0.42,
            "saliency_random_fraction": 0.48,
            "densify_weight_saliency": 0.75,
            "residual_detail_saliency_weight": 0.85,
            "region_weight_saliency_boost": 0.72,
            "saliency_sampling_gamma": 0.72,
            "residual_detail_fraction": 0.30,
            "residual_detail_percentile": 92.0,
            "residual_detail_sigma_min": 0.16,
            "residual_detail_sigma_max": 0.90,
            "residual_detail_edge_weight": 1.10,
            "residual_detail_edge_fraction": 0.68,
            "residual_detail_edge_percentile": 70.0,
            "residual_detail_edge_sigma_min": 0.06,
            "residual_detail_edge_sigma_max": 0.42,
            "residual_detail_edge_sigma_major_max": 0.95,
            "residual_detail_edge_alpha_boost": 0.10,
            "residual_detail_edge_color_gain": 1.18,
            "residual_detail_edge_saliency_weight": 1.05,
            "residual_detail_edge_aspect": 2.40,
            "residual_detail_color_gain": 1.08,
            "residual_detail_time_reserve_sec": 420.0,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.07,
        "residual_detail_passes": 1,
        "residual_detail_iters": 6,
    },
    "30m": {
        "label": "30m",
        "target_seconds": 1800.0,
        "stages": [80, 60, 40, 20],
        "splats_per_megapixel": 2500.0,
        "min_splats": 768,
        "max_splats": None,
        "coverage_sigma_cap_multiplier": 0.70,
        "refinement_overrides": {
            "base_layer_fraction": 0.30,
            "base_layer_alpha": 0.42,
            "initial_splat_fraction": 0.68,
            "initial_splat_cap": 3600,
            "edge_init_fraction": 0.52,
            "edge_init_percentile": 64.0,
            "edge_init_sigma_min": 0.42,
            "edge_init_sigma_max": 1.20,
            "edge_init_sigma_major_scale": 2.40,
            "edge_init_sigma_major_max": 3.10,
            "edge_init_alpha_min": 0.34,
            "edge_init_alpha_max": 0.78,
            "edge_init_saliency_weight": 0.85,
            "saliency_init_fraction": 0.46,
            "saliency_random_fraction": 0.52,
            "densify_weight_saliency": 0.85,
            "residual_detail_saliency_weight": 0.95,
            "region_weight_saliency_boost": 0.80,
            "saliency_sampling_gamma": 0.70,
            "residual_detail_edge_weight": 1.00,
            "residual_detail_edge_fraction": 0.58,
            "residual_detail_edge_percentile": 72.0,
            "residual_detail_edge_sigma_min": 0.07,
            "residual_detail_edge_sigma_max": 0.50,
            "residual_detail_edge_sigma_major_max": 1.10,
            "residual_detail_edge_alpha_boost": 0.08,
            "residual_detail_edge_color_gain": 1.12,
            "residual_detail_edge_saliency_weight": 0.95,
            "residual_detail_edge_aspect": 2.20,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.08,
        "residual_detail_passes": 1,
        "residual_detail_iters": 8,
    },
    "photo-native-10k": {
        "label": "photo native 10k",
        "target_seconds": 1200.0,
        "stages": [36, 20, 10],
        "splats_per_megapixel": 6500.0,
        "min_splats": 10000,
        "max_splats": 10000,
        "coverage_sigma_cap_multiplier": 0.78,
        "refinement_overrides": {
            # Start dense enough for native photos, but keep most of that
            # budget in stable color/shape support. The previous edge-heavy
            # 10k run proved that too many tangent strokes improve metrics
            # while making faces visibly noisy.
            "base_layer_fraction": 0.34,
            "base_layer_alpha": 0.38,
            "initial_splat_fraction": 0.64,
            "initial_splat_cap": 6400,
            "edge_init_fraction": 0.24,
            "edge_init_percentile": 62.0,
            "edge_init_sigma_min": 0.55,
            "edge_init_sigma_max": 1.60,
            "edge_init_sigma_major_scale": 1.70,
            "edge_init_sigma_major_max": 3.20,
            "edge_init_alpha_min": 0.18,
            "edge_init_alpha_max": 0.52,
            "edge_init_saliency_weight": 0.75,
            "edge_init_anisotropy_threshold": 1.20,
            "saliency_init_fraction": 0.58,
            "saliency_init_percentile": 48.0,
            "saliency_random_fraction": 0.60,
            "saliency_random_percentile": 45.0,
            "densify_fraction": 0.36,
            "densify_percentile": 64.0,
            "densify_weight_saliency": 1.00,
            "densify_weight_error": 0.40,
            "densify_weight_uncovered": 0.38,
            "densify_weight_edge": 0.12,
            "region_weight_saliency_boost": 0.92,
            "saliency_sampling_gamma": 0.62,
            "background_suppressed_saliency_enabled": True,
            "background_suppressed_saliency_use_for_sampling": True,
            "background_suppressed_saliency_use_for_weights": False,
            "background_suppressed_saliency_edge_gate": 0.80,
            "background_suppressed_saliency_focus_gate": 0.80,
            "background_suppressed_saliency_penalty_strength": 0.65,
            "renderer_tile_size": 24,
            "residual_detail_fraction": 0.14,
            "residual_detail_percentile": 76.0,
            "residual_detail_sigma_min": 0.22,
            "residual_detail_sigma_max": 1.05,
            "residual_detail_alpha_min": 0.12,
            "residual_detail_alpha_max": 0.58,
            "residual_detail_edge_weight": 0.45,
            "residual_detail_edge_fraction": 0.24,
            "residual_detail_edge_percentile": 62.0,
            "residual_detail_edge_sigma_min": 0.12,
            "residual_detail_edge_sigma_max": 0.58,
            "residual_detail_edge_sigma_major_max": 1.10,
            "residual_detail_edge_alpha_boost": 0.04,
            "residual_detail_edge_color_gain": 1.04,
            "residual_detail_edge_saliency_weight": 0.70,
            "residual_detail_edge_aspect": 1.80,
            "residual_detail_color_gain": 1.02,
            "coverage_sigma_max": 22.0,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.06,
        "residual_detail_passes": 2,
        "residual_detail_iters": 6,
    },
    "photo-native-20k": {
        "label": "photo native 20k",
        "target_seconds": 1800.0,
        "stages": [24, 12, 6],
        "splats_per_megapixel": 13000.0,
        "min_splats": 20000,
        "max_splats": 20000,
        "coverage_sigma_cap_multiplier": 0.74,
        "refinement_overrides": {
            # The 20k path is meant to test native-photo ceiling behavior, not
            # spend most of its budget on late edge confetti.
            "base_layer_fraction": 0.32,
            "base_layer_alpha": 0.38,
            "initial_splat_fraction": 1.00,
            "initial_splat_cap": 20000,
            "edge_init_fraction": 0.22,
            "edge_init_percentile": 62.0,
            "edge_init_sigma_min": 0.55,
            "edge_init_sigma_max": 1.60,
            "edge_init_sigma_major_scale": 1.70,
            "edge_init_sigma_major_max": 3.20,
            "edge_init_alpha_min": 0.18,
            "edge_init_alpha_max": 0.52,
            "edge_init_saliency_weight": 0.75,
            "edge_init_anisotropy_threshold": 1.20,
            "saliency_init_fraction": 0.58,
            "saliency_init_percentile": 48.0,
            "saliency_random_fraction": 0.60,
            "saliency_random_percentile": 45.0,
            "densify_fraction": 0.18,
            "densify_percentile": 66.0,
            "densify_weight_saliency": 1.00,
            "densify_weight_error": 0.40,
            "densify_weight_uncovered": 0.34,
            "densify_weight_edge": 0.12,
            "region_weight_saliency_boost": 0.92,
            "saliency_sampling_gamma": 0.62,
            "background_suppressed_saliency_enabled": True,
            "background_suppressed_saliency_use_for_sampling": True,
            "background_suppressed_saliency_use_for_weights": False,
            "background_suppressed_saliency_edge_gate": 0.80,
            "background_suppressed_saliency_focus_gate": 0.80,
            "background_suppressed_saliency_penalty_strength": 0.65,
            "renderer_tile_size": 24,
            "residual_detail_fraction": 0.08,
            "residual_detail_percentile": 78.0,
            "residual_detail_sigma_min": 0.18,
            "residual_detail_sigma_max": 0.92,
            "residual_detail_alpha_min": 0.10,
            "residual_detail_alpha_max": 0.48,
            "residual_detail_edge_weight": 0.38,
            "residual_detail_edge_fraction": 0.20,
            "residual_detail_edge_percentile": 64.0,
            "residual_detail_edge_sigma_min": 0.10,
            "residual_detail_edge_sigma_max": 0.50,
            "residual_detail_edge_sigma_major_max": 1.00,
            "residual_detail_edge_alpha_boost": 0.03,
            "residual_detail_edge_color_gain": 1.03,
            "residual_detail_edge_saliency_weight": 0.70,
            "residual_detail_edge_aspect": 1.70,
            "residual_detail_color_gain": 1.01,
            "coverage_sigma_max": 24.0,
        },
        "residual_detail_enabled": True,
        "residual_detail_reserve_fraction": 0.05,
        "residual_detail_passes": 1,
        "residual_detail_iters": 4,
    },
}
