#!/usr/bin/env python3
"""Regenerate README.md's measured-results block from the tracked ledgers.

The quality tables in README.md used to be hand-maintained, and they rotted:
the published 2k pixel-runtime LPIPS (0.2443) did not match the ledger it
claimed to summarize (0.2534). This tool makes that class of drift structural
rather than editorial. Every number between the ``corpus-results`` markers is
computed here, from data that is committed; nothing in the block is typed.

Sources, in order of authority:

- ``src/splatthis/data/compositor-fidelity.json`` -- the published expectation
  registry (deployed and compositor-only fidelity for the declarative
  emitters, with per-image evidence). Its medians are cross-checked against
  its own per-image tables and the tool refuses to publish on mismatch.
- ``data/pptx-order-compositor-corpus.json`` -- the 21-image real-PowerPoint
  painter-order corpus.
- ``data/svg-compositor-corpus.json`` -- the browser SVG painter-order and
  gate-selection corpus.
- ``result/corpus/results.jsonl`` -- the governing browser ledger. Only rows
  with ``is_deployed_artifact`` are read, per result/README.md.
- ``result/svg-quality/measurements.json`` -- emitted SVG sizes and
  compositor SSIM per image; independently cross-checks the registry.

Usage::

    python tools/update_readme.py            # rewrite the README block
    python tools/update_readme.py --check    # exit non-zero if it is stale

``tests/unit/test_readme_results.py`` runs ``--check``, so a ledger change
that is not reflected in README.md fails CI.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO = Path(__file__).resolve().parents[1]
README = REPO / "README.md"
FIDELITY = REPO / "src" / "splatthis" / "data" / "compositor-fidelity.json"
PPTX_CORPUS = REPO / "data" / "pptx-order-compositor-corpus.json"
SVG_CORPUS = REPO / "data" / "svg-compositor-corpus.json"
SVG_CORPUS_V2 = REPO / "data" / "svg-compositor-corpus-v2.json"
RESULTS = REPO / "result" / "corpus" / "results.jsonl"
SVG_SIZES = REPO / "result" / "svg-quality" / "measurements.json"

BEGIN = (
    "<!-- corpus-results:begin -- generated by tools/update_readme.py; "
    "edit the ledgers, not this block -->"
)
END = "<!-- corpus-results:end -->"

CORPUS_IMAGES = 21

#: The 2k pixel-runtime pass that covers the whole corpus.
PIXEL_2K_TAG = "long-full-v1"
#: Effective-4k passes, newest first; the newest row per image governs.
PIXEL_4K_TAGS = (
    "canvas-scale-effective-stage-gated-v3",
    "canvas-scale-effective-monotonic-v2",
    "canvas-scale-effective-v1",
)


class LedgerError(RuntimeError):
    """A ledger is missing, incomplete, or inconsistent with itself."""


def _load_json(path: Path) -> Any:
    if not path.is_file():
        raise LedgerError(f"missing ledger: {path.relative_to(REPO)}")
    return json.loads(path.read_text(encoding="utf-8"))


def _median(values: List[float]) -> float:
    if not values:
        raise LedgerError("median of nothing")
    return statistics.median(values)


def _percentile(values: List[float], q: float) -> float:
    """Linear-interpolation percentile, numpy's default method."""
    if not values:
        raise LedgerError("percentile of nothing")
    ordered = sorted(values)
    position = (len(ordered) - 1) * q
    low = int(position)
    high = min(low + 1, len(ordered) - 1)
    fraction = position - low
    return ordered[low] * (1 - fraction) + ordered[high] * fraction


def _require_corpus(images: set, what: str) -> None:
    if len(images) != CORPUS_IMAGES:
        raise LedgerError(
            f"{what}: expected {CORPUS_IMAGES} corpus images, found {len(images)}"
        )


def load_deployed_rows() -> List[Dict[str, Any]]:
    if not RESULTS.is_file():
        raise LedgerError(f"missing ledger: {RESULTS.relative_to(REPO)}")
    rows = [json.loads(line) for line in RESULTS.read_text().splitlines() if line]
    # result/README.md: rows without is_deployed_artifact are proxies or
    # pre-governing schema and must not feed a published statistic.
    return [
        r
        for r in rows
        if r.get("is_deployed_artifact") is True and r.get("returncode") == 0
    ]


def pixel_runtime_rows() -> Dict[str, Dict[str, Dict[str, Any]]]:
    """Per-image governing rows for the 2k and effective-4k passes.

    The ledger is append-only and images were re-run as the harness evolved,
    so several rows can share one (image, run_tag). The newest row -- the last
    in file order, from the newest tag -- is the governing evidence.
    """
    deployed = load_deployed_rows()
    two_k = {r["image"]: r for r in deployed if r.get("run_tag") == PIXEL_2K_TAG}
    four_k: Dict[str, Dict[str, Any]] = {}
    for tag in reversed(PIXEL_4K_TAGS):
        for r in deployed:
            if r.get("run_tag") == tag:
                four_k[r["image"]] = r
    _require_corpus(set(two_k), f"pixel-runtime 2k ({PIXEL_2K_TAG})")
    _require_corpus(set(four_k), "pixel-runtime effective-4k union")
    for r in list(two_k.values()) + list(four_k.values()):
        if r.get("seed") != 0:
            raise LedgerError(
                f"pixel-runtime row {r.get('key')!r} is seed {r.get('seed')}; "
                f"this block publishes seed-0 figures only"
            )
    return {"2k": two_k, "4k": four_k}


def declarative_expectations() -> Dict[str, Any]:
    """The published registry, cross-checked before anything is republished.

    Three checks, because each has failed in this repository's history: the
    published medians against the registry's own per-image tables (deployed
    LPIPS and SSIM, compositor LPIPS), and the compositor SSIM medians against
    ``result/svg-quality/measurements.json``, a ledger the registry did not
    derive them from.
    """
    data = _load_json(FIDELITY)

    def pin(fmt: str, what: str, published: float, recomputed: float) -> None:
        if abs(published - recomputed) > 5e-5:
            raise LedgerError(
                f"{FIDELITY.name} formats[{fmt}] publishes {what} {published} "
                f"but the evidence medians to {recomputed:.4f}; refusing to "
                f"publish an inconsistent registry"
            )

    for fmt in ("svg", "svg-high", "css"):
        expectation = data["formats"][fmt]["expectation"]
        per_image = data["per_image"][fmt]
        _require_corpus({p["image"] for p in per_image}, f"per_image[{fmt}]")
        deployed = expectation["deployed"]
        lpips = [p["deployed_lpips"] for p in per_image]
        ssim = [p["deployed_ssim_srgb"] for p in per_image]
        pin(fmt, "deployed LPIPS median", deployed["lpips_median"], _median(lpips))
        pin(fmt, "deployed LPIPS p90", deployed["lpips_p90"], _percentile(lpips, 0.9))
        pin(fmt, "deployed SSIM median", deployed["ssim_srgb_median"], _median(ssim))
        pin(fmt, "deployed SSIM p10", deployed["ssim_srgb_p10"], _percentile(ssim, 0.1))
        pin(
            fmt,
            "compositor LPIPS median",
            expectation["compositor"]["lpips_median"],
            _median([p["compositor_lpips"] for p in per_image]),
        )

    measurements = _load_json(SVG_SIZES)
    for fmt, quality in (("svg", "standard"), ("svg-high", "high")):
        pin(
            fmt,
            "compositor SSIM median",
            data["formats"][fmt]["expectation"]["compositor"]["ssim_srgb_median"],
            _median([measurements[image][quality][0] for image in measurements]),
        )

    runtime = data["formats"]["pixel-runtime"]["expectation"]["deployed"]
    runtime_rows = data["per_image"]["pixel-runtime"]
    _require_corpus({p["image"] for p in runtime_rows}, "per_image[pixel-runtime]")
    r_lpips = [p["deployed_lpips"] for p in runtime_rows]
    r_ssim = [p["deployed_ssim_srgb"] for p in runtime_rows]
    pin(
        "pixel-runtime",
        "deployed LPIPS median",
        runtime["lpips_median"],
        _median(r_lpips),
    )
    pin(
        "pixel-runtime",
        "deployed LPIPS p90",
        runtime["lpips_p90"],
        _percentile(r_lpips, 0.9),
    )
    pin(
        "pixel-runtime",
        "deployed SSIM median",
        runtime["ssim_srgb_median"],
        _median(r_ssim),
    )
    pin(
        "pixel-runtime",
        "deployed SSIM p10",
        runtime["ssim_srgb_p10"],
        _percentile(r_ssim, 0.1),
    )
    return data


def svg_size_medians_kb() -> Dict[str, float]:
    sizes = _load_json(SVG_SIZES)
    _require_corpus(set(sizes), "svg-quality measurements")
    return {
        quality: _median([sizes[image][quality][1] for image in sizes])
        for quality in ("standard", "high")
    }


def _row_med(rows: Dict[str, Dict[str, Any]], key: str) -> float:
    return _median([r[key] for r in rows.values() if r.get(key) is not None])


def build_block() -> str:
    registry = declarative_expectations()
    formats = registry["formats"]
    sizes_kb = svg_size_medians_kb()
    pixels = pixel_runtime_rows()
    pptx = _load_json(PPTX_CORPUS)
    svg_gate = _load_json(SVG_CORPUS)["seed0_medians"]["artifact_gate_selection"]
    gate_v2 = _load_json(SVG_CORPUS_V2)["seed0_medians"]["artifact_gate_selection"]

    def deployed(fmt: str) -> Dict[str, float]:
        return formats[fmt]["expectation"]["deployed"]

    def compositor(fmt: str) -> Dict[str, float]:
        return formats[fmt]["expectation"]["compositor"]

    lines: List[str] = [BEGIN, ""]
    out = lines.append

    out(
        f"Numbers in this block are computed from the committed ledgers by "
        f"`tools/update_readme.py`; `tests/unit/test_readme_results.py` fails "
        f"when they go stale. All are seed-0 measurements over the "
        f"{CORPUS_IMAGES}-image governing corpus at a maximum edge of roughly "
        f"384 px, scored on the deployed artifact in its governing renderer -- "
        f"Chromium for the browser targets, Microsoft PowerPoint for the deck."
    )
    out("")

    out(
        "**Declarative emitters.** One fitted population per image, emitted "
        "by the current exporters and compared with the original image:"
    )
    out("")
    out("| Artifact | LPIPS ↓ median | LPIPS p90 | SSIM median | Median size |")
    out("|---|---:|---:|---:|---:|")
    declarative = (
        ("SVG (`standard` gradients, default)", "svg", sizes_kb["standard"]),
        ("SVG (`--svg-gradient-quality high`)", "svg-high", sizes_kb["high"]),
        ("Scriptless CSS", "css", None),
    )
    for label, fmt, size_kb in declarative:
        d = deployed(fmt)
        size = f"{size_kb:,.0f} KB" if size_kb is not None else "not measured"
        out(
            f"| {label} | {d['lpips_median']:.4f} | {d['lpips_p90']:.4f} "
            f"| {d['ssim_srgb_median']:.4f} | {size} |"
        )
    out("")
    v2_counts = gate_v2["selected_counts"]
    out(
        f"The rows above measure each emitter family unconditionally. A bare "
        f"default run (`max-fidelity` profile) additionally applies the SVG "
        f"compositor gate, which chooses per image against the default "
        f"corrected-standard emitter as incumbent. Validated on the corpus "
        f"after the 0.2.6 incumbent change: the gate kept `high` gradients "
        f"on {v2_counts.get('corrected-high', 0)} images and the default "
        f"`standard` on {v2_counts.get('corrected-standard', 0)}, never "
        f"legacy, for gate medians of SSIM {gate_v2['ssim_srgb']:.4f} / "
        f"LPIPS {gate_v2['lpips']:.4f} -- up from "
        f"{svg_gate['ssim_srgb']:.4f} under the July legacy incumbent."
    )
    out("")
    out(registry["headline"])
    out("")

    out(
        f"**Fitted and deployed, per format.** Each format trains against "
        f"its own export target; this is best-effort per format, not one "
        f"splat set exported several ways. The pixel-runtime rows are the "
        f"historical governing ledger passes; an August 2026 re-emission of "
        f"all 21 artifacts from current code reproduced the 2k medians "
        f"exactly (LPIPS "
        f"{formats['pixel-runtime']['expectation']['deployed']['lpips_median']:.4f}"
        f" / SSIM "
        f"{formats['pixel-runtime']['expectation']['deployed']['ssim_srgb_median']:.4f}"
        f'), so the ledger and `expected_fidelity("pixel-runtime")` agree:'
    )
    out("")
    out(
        "| Artifact | Budget | Median final splats | SSIM ↑ | LPIPS ↓ "
        "| Median size | Median training |"
    )
    out("|---|---:|---:|---:|---:|---:|---:|")
    for label, rows, budget in (
        ("Pixel runtime HTML", pixels["2k"], "2k"),
        ("Pixel runtime HTML", pixels["4k"], "effective 4k"),
    ):
        out(
            f"| {label} | {budget} | {_row_med(rows, 'splats_final'):,.0f} "
            f"| {_row_med(rows, 'ssim_srgb'):.4f} | {_row_med(rows, 'lpips'):.4f} "
            f"| {_row_med(rows, 'artifact_bytes') / 1024:,.0f} KB "
            f"| {_row_med(rows, 'runtime_sec') / 60:.1f} min |"
        )
    pptx_splats = _median([p["splats"] for p in pptx["per_image"]])
    for label, key in (
        ("PowerPoint (back-to-front order, default)", "corrected_order"),
        ("PowerPoint (`--pptx-painter-order legacy`)", "legacy_order"),
    ):
        med = pptx["medians"][key]
        out(
            f"| {label} | 2k | {pptx_splats:,.0f} | {med['ssim_srgb']:.4f} "
            f"| {med['lpips']:.4f} | {med['file_size_bytes'] / 1024:,.0f} KB "
            f"| not recorded |"
        )
    out("")
    counts = pptx["selection_counts"]
    out(
        f"The strict PowerPoint artifact gate, choosing per image, kept the "
        f"corrected order on {counts['corrected-order']} of "
        f"{CORPUS_IMAGES} images and legacy on {counts['legacy-order']}; "
        f"corrected is the default as of 0.2.6, and legacy remains available "
        f"for the rare regressing image."
    )
    out("")

    improved = sum(
        1
        for image, row in pixels["2k"].items()
        if pixels["4k"][image]["ssim_srgb"] > row["ssim_srgb"]
        and pixels["4k"][image]["lpips"] < row["lpips"]
    )
    render_ms = _row_med(pixels["4k"], "browser_render_ms")
    best_ssim = max(r["ssim_srgb"] for r in pixels["4k"].values())
    out(
        f"{improved} of {CORPUS_IMAGES} images improved from 2k to effective "
        f"4k in both SSIM and LPIPS. The effective-4k runtime rendered in a "
        f"median {render_ms:.0f} ms in Chrome. None reached 0.99 SSIM "
        f"(best {best_ssim:.4f})."
    )
    out("")

    out(
        "**Emitter loss alone** (the same splats through the deployed "
        "compositor versus the internal reference render -- the number that "
        "matters only if you supply your own splats): median LPIPS "
        + ", ".join(
            f"{compositor(fmt)['lpips_median']:.4f} ({fmt})"
            for fmt in ("svg", "svg-high", "css", "pixel-runtime")
        )
        + ". Query it programmatically with `splatthis.expected_fidelity()`."
    )
    out("")

    out("<details>")
    out(
        "<summary>Per-image deployed LPIPS for the declarative emitters "
        "(lower is better)</summary>"
    )
    out("")
    out("| Image | SVG | SVG high | CSS |")
    out("|---|---:|---:|---:|")
    per_image = {
        fmt: {p["image"]: p for p in registry["per_image"][fmt]}
        for fmt in ("svg", "svg-high", "css")
    }
    for image in sorted(
        per_image["svg"], key=lambda i: per_image["svg"][i]["deployed_lpips"]
    ):
        out(
            f"| {image} "
            f"| {per_image['svg'][image]['deployed_lpips']:.4f} "
            f"| {per_image['svg-high'][image]['deployed_lpips']:.4f} "
            f"| {per_image['css'][image]['deployed_lpips']:.4f} |"
        )
    out("")
    out("</details>")
    out("")
    out(END)
    return "\n".join(lines)


def render_readme() -> str:
    text = README.read_text(encoding="utf-8")
    begin = text.find(BEGIN)
    end = text.find(END)
    if begin == -1 or end == -1:
        raise LedgerError(f"README.md does not contain the {BEGIN!r} / {END!r} markers")
    return text[:begin] + build_block() + text[end + len(END) :]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify README.md matches the ledgers without writing",
    )
    args = parser.parse_args()

    try:
        rendered = render_readme()
    except LedgerError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    current = README.read_text(encoding="utf-8")
    if args.check:
        if current != rendered:
            print(
                "README.md is stale: the corpus-results block no longer "
                "matches the ledgers. Run `python tools/update_readme.py`.",
                file=sys.stderr,
            )
            return 1
        print("README.md corpus-results block is current.")
        return 0

    if current == rendered:
        print("README.md already current; nothing written.")
        return 0
    README.write_text(rendered, encoding="utf-8")
    print("README.md corpus-results block regenerated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
