#!/usr/bin/env python3
"""Regenerate the number-bearing regions of the GitHub Pages landing page.

``docs/index.html`` showcases artifacts and quotes their scores. Three of its
regions carry ledger numbers -- the hero SVG card, the SVG compositor
evidence table, and the one-image-every-exporter table -- and are generated
here from the same versioned ledgers as the README block and the paper,
reusing ``tools/update_readme.py``'s loaders and cross-checks. Prose and
artifact choices stay hand-written; numbers do not.

Usage::

    python tools/update_landing.py            # rewrite the generated regions
    python tools/update_landing.py --check    # exit non-zero if stale

``tests/unit/test_landing_page.py`` runs ``--check`` in CI.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path
from typing import Any, Dict, List

REPO = Path(__file__).resolve().parents[1]
LANDING = REPO / "docs" / "index.html"
HERO_SVG = REPO / "docs" / "demo" / "chameleon.svg"
PPTX_DECK = REPO / "docs" / "demo" / "chameleon.pptx"
PPTX_CAPTURE = REPO / "docs" / "demo" / "chameleon-pptx.png"

MARKER_NOTE = "generated by tools/update_landing.py; edit the ledgers, not this block"


def _load_readme_tool() -> Any:
    spec = importlib.util.spec_from_file_location(
        "update_readme", Path(__file__).with_name("update_readme.py")
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


TOOL = _load_readme_tool()


def _chameleon(registry: Dict[str, Any], fmt: str) -> Dict[str, float]:
    for row in registry["per_image"][fmt]:
        if row["image"] == "chameleon":
            return row
    raise TOOL.LedgerError(f"no chameleon row in per_image[{fmt}]")


def hero_fragment(registry: Dict[str, Any]) -> str:
    """The hero card: the shipped showcase SVG with its ledger scores.

    ``docs/demo/chameleon.svg`` is the high-gradient showcase winner, so its
    scores are the registry's svg-high chameleon row; the caption refuses to
    render if the artifact disappears.
    """
    if not HERO_SVG.is_file():
        raise TOOL.LedgerError(f"missing hero artifact: {HERO_SVG.relative_to(REPO)}")
    row = _chameleon(registry, "svg-high")
    # LF-normalized so a CRLF-converting checkout quotes the same size.
    size_mb = len(HERO_SVG.read_bytes().replace(b"\r\n", b"\n")) / 1048576
    return (
        "  <figure>\n"
        '    <object data="demo/chameleon.svg" type="image/svg+xml" '
        'style="width:100%;height:auto;display:block;border-radius:4px">'
        "</object>\n"
        f"    <figcaption><strong>SVG</strong> · corrected exporter, high "
        f"gradients · SSIM {row['deployed_ssim_srgb']:.4f} · LPIPS "
        f"{row['deployed_lpips']:.4f} · {size_mb:.1f} MB live vector"
        "</figcaption>\n"
        "  </figure>"
    )


def evidence_fragment() -> str:
    medians = TOOL._load_json(TOOL.SVG_CORPUS)["seed0_medians"]
    rows = (
        ("Historical order", medians["legacy_order"]),
        ("Correct order, standard stops", medians["corrected_standard"]),
        ("Correct order, high stops", medians["corrected_high"]),
        ("Per-image artifact gate", medians["artifact_gate_selection"]),
    )
    cells = "\n".join(
        f"    <tr><td>{label}</td><td>{m['ssim_srgb']:.4f}</td>"
        f"<td>{m['lpips']:.4f}</td>"
        f"<td>{m['gzip_size_bytes'] / 1024:.1f} KB</td>"
        f"<td>{m['capture_time_ms']:.0f} ms</td></tr>"
        for label, m in rows
    )
    return (
        "<table>\n"
        "  <thead><tr><th>SVG policy</th><th>SSIM</th><th>LPIPS↓</th>"
        "<th>gzip</th><th>Capture</th></tr></thead>\n"
        f"  <tbody>\n{cells}\n  </tbody>\n"
        "</table>"
    )


def chameleon_fragment(registry: Dict[str, Any]) -> str:
    deployed_rows: List[tuple] = []

    pixel = None
    for line in TOOL.RESULTS.read_text(encoding="utf-8").splitlines():
        if line:
            row = json.loads(line)
            if (
                row.get("is_deployed_artifact") is True
                and row.get("run_tag") == TOOL.PIXEL_2K_TAG
                and row["image"] == "chameleon"
            ):
                pixel = row  # append-only ledger: the last row governs
    if pixel is None:
        raise TOOL.LedgerError("no governing chameleon pixel-runtime row")
    deployed_rows.append(
        ("Pixel runtime (2k ledger)", pixel["ssim_srgb"], pixel["lpips"], "own fit")
    )

    for label, fmt in (
        ("SVG, standard gradients", "svg"),
        ("SVG, high gradients", "svg-high"),
        ("Scriptless CSS", "css"),
    ):
        row = _chameleon(registry, fmt)
        deployed_rows.append(
            (label, row["deployed_ssim_srgb"], row["deployed_lpips"], "shared fit")
        )

    pptx = TOOL._load_json(TOOL.PPTX_CORPUS)
    cham = next((p for p in pptx["per_image"] if p["image"] == "chameleon"), None)
    if cham is None:
        raise TOOL.LedgerError("no chameleon row in the PPTX order corpus")
    for label, key in (
        ("PowerPoint, corrected order", "corrected_order"),
        ("PowerPoint, legacy order (default)", "legacy_order"),
    ):
        deployed_rows.append(
            (label, cham[key]["ssim_srgb"], cham[key]["lpips"], "own fit")
        )

    cells = "\n".join(
        f"    <tr><td>{label}</td><td>{ssim:.4f}</td><td>{lpips:.4f}</td>"
        f"<td>{note}</td></tr>"
        for label, ssim, lpips, note in deployed_rows
    )
    return (
        "<table>\n"
        "  <thead><tr><th>Format</th><th>SSIM</th><th>LPIPS↓</th>"
        "<th>Population</th></tr></thead>\n"
        f"  <tbody>\n{cells}\n  </tbody>\n"
        "</table>\n"
        '<p class="note">Chameleon, deployed artifact against the source in '
        "its governing renderer — Chromium for the browser targets, real "
        "PowerPoint for the deck. The SVG and CSS rows share one splat "
        "population, so their differences are purely compositor; the pixel "
        "runtime and PowerPoint rows are separately trained runs.</p>"
    )


def _pptx_chameleon(pptx: Dict[str, Any]) -> Dict[str, Any]:
    row = next((p for p in pptx["per_image"] if p["image"] == "chameleon"), None)
    if row is None:
        raise TOOL.LedgerError("no chameleon row in the PPTX order corpus")
    return row


def pptx_fragment() -> str:
    """The PowerPoint capture card with its ledger scores.

    The shipped demo deck is the legacy-order (CLI default) build of the
    order-study's chameleon population, so its scores are that ledger's
    legacy_order row.
    """
    for asset in (PPTX_DECK, PPTX_CAPTURE):
        if not asset.is_file():
            raise TOOL.LedgerError(f"missing demo asset: {asset.relative_to(REPO)}")
    row = _pptx_chameleon(TOOL._load_json(TOOL.PPTX_CORPUS))
    legacy = row["legacy_order"]
    size_kb = PPTX_DECK.stat().st_size / 1024
    return (
        "  <figure>\n"
        '    <img src="demo/chameleon-pptx.png" '
        'alt="Real Microsoft PowerPoint slideshow capture of the deck">\n'
        f"    <figcaption><strong>PowerPoint</strong> · "
        f"{row['splats']:,} native DrawingML shapes · SSIM "
        f"{legacy['ssim_srgb']:.4f} · LPIPS {legacy['lpips']:.4f} · "
        f"{size_kb:.0f} KB deck</figcaption>\n"
        "  </figure>"
    )


def _splice(text: str, name: str, replacement: str) -> str:
    begin = f"<!-- {name}:begin -- {MARKER_NOTE} -->"
    end = f"<!-- {name}:end -->"
    start = text.find(begin)
    stop = text.find(end)
    if start == -1 or stop == -1:
        raise TOOL.LedgerError(f"docs/index.html is missing the {name} markers")
    return text[: start + len(begin)] + "\n" + replacement + "\n" + text[stop:]


def render() -> str:
    registry = TOOL.declarative_expectations()
    text = LANDING.read_text(encoding="utf-8")
    text = _splice(text, "landing-svg-hero", hero_fragment(registry))
    text = _splice(text, "landing-pptx", pptx_fragment())
    text = _splice(text, "landing-svg-evidence", evidence_fragment())
    text = _splice(text, "landing-chameleon", chameleon_fragment(registry))
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify docs/index.html matches the ledgers without writing",
    )
    args = parser.parse_args()

    try:
        rendered = render()
    except TOOL.LedgerError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    current = LANDING.read_text(encoding="utf-8")
    if args.check:
        if current != rendered:
            print(
                "docs/index.html is stale: the generated regions no longer "
                "match the ledgers. Run `python tools/update_landing.py`.",
                file=sys.stderr,
            )
            return 1
        print("docs/index.html generated regions are current.")
        return 0

    if current == rendered:
        print("docs/index.html already current; nothing written.")
        return 0
    LANDING.write_text(rendered, encoding="utf-8")
    print("docs/index.html generated regions rewritten.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
