#!/usr/bin/env python3
"""Regenerate the paper's living results section and render the Pages paper.

``paper/report.md`` is the source of truth. Its historical sections are dated
and frozen; the one section that must track the repository -- §5.4, the
corrected-emitter results -- is regenerated here from the same versioned
ledgers that feed ``tools/update_readme.py``, whose loaders and cross-checks
this tool imports rather than reimplements. The report is then rendered to
``docs/paper/index.html`` so GitHub Pages serves it as a styled paper.

Usage::

    python tools/update_paper.py            # rewrite §5.4 and the HTML page
    python tools/update_paper.py --check    # exit non-zero if either is stale

``tests/unit/test_paper_page.py`` runs ``--check``, so a ledger change that
is not reflected in the published paper fails CI.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from pathlib import Path
from typing import Any, Dict, List

import markdown

REPO = Path(__file__).resolve().parents[1]
PAPER_MD = REPO / "paper" / "report.md"
PAPER_HTML = REPO / "docs" / "paper" / "index.html"
RESULTS = REPO / "result" / "corpus" / "results.jsonl"
VERSION_FILE = REPO / "src" / "splatthis" / "_version.py"

BEGIN = (
    "<!-- current-emitters:begin -- generated by tools/update_paper.py "
    "from the versioned ledgers; edit the ledgers, not this block -->"
)
END = "<!-- current-emitters:end -->"

TITLE = "Deploying 2D Gaussian Splats to Vector Document Formats"
PAPER_URL = "https://bramalkema.github.io/SplatThis/paper/"


def _load_readme_tool() -> Any:
    spec = importlib.util.spec_from_file_location(
        "update_readme", Path(__file__).with_name("update_readme.py")
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


TOOL = _load_readme_tool()


def _version() -> str:
    match = re.search(r'__version__ = "([^"]+)"', VERSION_FILE.read_text())
    if not match:
        raise TOOL.LedgerError(f"no __version__ in {VERSION_FILE}")
    return match.group(1)


def _content_classes() -> Dict[str, str]:
    classes: Dict[str, str] = {}
    for line in RESULTS.read_text(encoding="utf-8").splitlines():
        if line:
            row = json.loads(line)
            if "content_class" in row:
                classes[row["image"]] = row["content_class"]
    if len(classes) != TOOL.CORPUS_IMAGES:
        raise TOOL.LedgerError(
            f"content classes cover {len(classes)} images, "
            f"expected {TOOL.CORPUS_IMAGES}"
        )
    return classes


def build_section() -> str:
    """§5.4, derived entirely from cross-checked ledgers."""
    registry = TOOL.declarative_expectations()
    sizes_kb = TOOL.svg_size_medians_kb()
    svg_corpus = TOOL._load_json(TOOL.SVG_CORPUS)["seed0_medians"]
    legacy = svg_corpus["legacy_order"]
    gate = svg_corpus["artifact_gate_selection"]
    classes = _content_classes()

    def deployed(fmt: str) -> Dict[str, float]:
        return registry["formats"][fmt]["expectation"]["deployed"]

    def compositor(fmt: str) -> Dict[str, float]:
        return registry["formats"][fmt]["expectation"]["compositor"]

    per_image = {
        fmt: {p["image"]: p for p in registry["per_image"][fmt]}
        for fmt in ("svg", "svg-high", "css")
    }

    lines: List[str] = [BEGIN, ""]
    out = lines.append

    out("### 5.4 Corrected emitters and the fit/emitter split (August 2026)")
    out("")
    out(
        "This section is regenerated from the repository's versioned ledgers "
        "(`compositor-fidelity.json`, `svg-compositor-corpus.json`, "
        "`svg-quality/measurements.json`); every published median is "
        "re-derived from its per-image evidence before rendering, and the "
        "build fails on any mismatch."
    )
    out("")
    out(
        "Applying §3.2 -- paint order and exact stop sampling -- to the same "
        "populations, deployed against the original image in governing "
        "Chromium:"
    )
    out("")
    out("| emitter | LPIPS ↓ median | LPIPS p90 | SSIM median | median size |")
    out("|---|---:|---:|---:|---:|")
    out(
        f"| legacy order (baseline, §5.3) | {legacy['lpips']:.4f} | — "
        f"| {legacy['ssim_srgb']:.4f} | — |"
    )
    for label, fmt, size in (
        ("SVG, `standard` gradients", "svg", f"{sizes_kb['standard']:,.0f} KB"),
        ("SVG, `high` gradients", "svg-high", f"{sizes_kb['high']:,.0f} KB"),
        ("scriptless CSS", "css", "—"),
    ):
        d = deployed(fmt)
        out(
            f"| {label} | {d['lpips_median']:.4f} | {d['lpips_p90']:.4f} "
            f"| {d['ssim_srgb_median']:.4f} | {size} |"
        )
    out("")

    svg_ratio = deployed("svg")["lpips_median"] / compositor("svg")["lpips_median"]
    high_ratio = (
        deployed("svg-high")["lpips_median"] / compositor("svg-high")["lpips_median"]
    )
    out(
        f"The correction roughly halves deployed error "
        f"({legacy['lpips']:.4f} → {deployed('svg')['lpips_median']:.4f} median "
        f"LPIPS) and collapses the emitters: the three declarative targets "
        f"span 0.001 median LPIPS, below the §5.2 noise floor. Isolating the "
        f"emitter term -- the same splats through the deployed compositor "
        f"versus the internal reference render -- shows why:"
    )
    out("")
    out("| emitter | LPIPS median | SSIM median |")
    out("|---|---:|---:|")
    for label, fmt in (
        ("SVG, `standard`", "svg"),
        ("SVG, `high`", "svg-high"),
        ("scriptless CSS", "css"),
        ("pixel runtime", "pixel-runtime"),
    ):
        c = compositor(fmt)
        out(f"| {label} | {c['lpips_median']:.4f} | {c['ssim_srgb_median']:.4f} |")
    out("")
    out(
        f"Deployed error is {svg_ratio:.0f}x the emitter's own loss for "
        f"standard gradients and {high_ratio:.0f}x for high: the fit, not the "
        f"format, is the limit. " + registry["headline"]
    )
    out("")

    out("Per content class, deployed median LPIPS on the corrected emitters:")
    out("")
    out("| content class | n | SVG | SVG high | CSS |")
    out("|---|---:|---:|---:|---:|")
    by_class: Dict[str, List[str]] = {}
    for image, cls in classes.items():
        by_class.setdefault(cls, []).append(image)

    def class_median(fmt: str, images: List[str]) -> float:
        return TOOL._median(
            [per_image[fmt][image]["deployed_lpips"] for image in images]
        )

    ranked = sorted(by_class.items(), key=lambda item: -class_median("svg", item[1]))
    for cls, images in ranked:
        out(
            f"| {cls} | {len(images)} | {class_median('svg', images):.4f} "
            f"| {class_median('svg-high', images):.4f} "
            f"| {class_median('css', images):.4f} |"
        )
    out("")

    counts = gate["selected_counts"]
    out(
        f"The default per-image artifact gate, racing each candidate against "
        f"a legacy-order incumbent, kept `high` gradients on "
        f"{counts['corrected-high']} of {TOOL.CORPUS_IMAGES} images, legacy "
        f"order on {counts['legacy-order']}, and `standard` on "
        f"{counts['corrected-standard']}, for gate medians of "
        f"{gate['ssim_srgb']:.4f} SSIM / {gate['lpips']:.4f} LPIPS. The fixed "
        f"corrected-high choice beats the gate at the median -- an incumbent "
        f"bias recorded, like the PPTX default of §6, as an open decision."
    )
    out("")
    out(END)
    return "\n".join(lines)


def render_markdown() -> str:
    text = PAPER_MD.read_text(encoding="utf-8")
    begin = text.find(BEGIN)
    end = text.find(END)
    if begin == -1 or end == -1:
        raise TOOL.LedgerError(f"{PAPER_MD} does not contain the §5.4 markers")
    return text[:begin] + build_section() + text[end + len(END) :]


PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="description" content="Technical report: fitting 2D Gaussian splats \
to single images and deploying them to SVG, scriptless CSS, and PowerPoint \
DrawingML, graded on the deployed artifact in its governing renderer.">
<style>
  * {{ box-sizing: border-box; }}
  html {{ background: #fff; }}
  body {{
    margin: 0 auto; padding: 3.5rem 1.25rem 5rem; max-width: 46rem;
    font-family: Charter, Georgia, "Times New Roman", serif;
    font-size: 1.0625rem; line-height: 1.55; color: #1b1b1b;
  }}
  nav {{ font-family: system-ui, sans-serif; font-size: .85rem; margin-bottom: 2.5rem; }}
  nav a {{ color: #444; }}
  h1 {{ font-size: 1.75rem; line-height: 1.25; letter-spacing: -0.01em; margin: 0 0 .5rem; }}
  h1 + p {{ font-family: system-ui, sans-serif; font-size: .85rem; color: #555; }}
  h2 {{ font-size: 1.25rem; margin: 2.5rem 0 .75rem; }}
  h3 {{ font-size: 1.05rem; margin: 2rem 0 .5rem; }}
  p {{ margin: .75rem 0; }}
  a {{ color: #1a4f8b; }}
  em {{ font-style: italic; }}
  code {{ font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: .85em;
         background: #f4f4f2; padding: .1em .3em; border-radius: 3px; }}
  table {{ border-collapse: collapse; margin: 1.25rem auto; font-size: .9rem;
          font-variant-numeric: tabular-nums; }}
  th, td {{ padding: .35rem .8rem; }}
  thead th {{ border-top: 1.5px solid #1b1b1b; border-bottom: .75px solid #1b1b1b;
             font-weight: 600; }}
  tbody tr:last-child td {{ border-bottom: 1.5px solid #1b1b1b; }}
  ul, ol {{ padding-left: 1.4rem; }}
  li {{ margin: .4rem 0; }}
  footer {{ margin-top: 3.5rem; border-top: .75px solid #ccc; padding-top: 1.5rem; }}
  footer pre {{ background: #f4f4f2; padding: 1rem; border-radius: 6px;
              font-size: .8rem; overflow-x: auto; }}
  @media print {{ nav, footer {{ display: none; }} body {{ padding: 0; }} }}
  @media (prefers-color-scheme: dark) {{
    html {{ background: #101012; }}
    body {{ color: #e8e8e4; }}
    nav a {{ color: #aaa; }}
    a {{ color: #7fb0e8; }}
    code, footer pre {{ background: #1c1c20; }}
    thead th {{ border-color: #e8e8e4; }}
    tbody tr:last-child td {{ border-color: #e8e8e4; }}
  }}
</style>
</head>
<body>
<nav><a href="../">&larr; SplatThis project page</a> &middot;
<a href="https://github.com/BramAlkema/SplatThis">code</a> &middot;
<a href="https://github.com/BramAlkema/SplatThis/blob/main/paper/report.md">markdown source</a></nav>
<article>
{content}
</article>
<footer>
<h2>Citing this report</h2>
<pre>@techreport{{alkema2026splats,
  author      = {{Alkema, Bram}},
  title       = {{{title}}},
  institution = {{SplatThis project}},
  year        = {{2026}},
  note        = {{SplatThis v{version}}},
  url         = {{{url}}}
}}</pre>
</footer>
</body>
</html>
"""


def render_html(report_md: str) -> str:
    content = markdown.markdown(report_md, extensions=["tables"])
    return PAGE_TEMPLATE.format(
        title=TITLE, content=content, version=_version(), url=PAPER_URL
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify the report and the Pages HTML match the ledgers",
    )
    args = parser.parse_args()

    try:
        report = render_markdown()
        page = render_html(report)
    except TOOL.LedgerError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    current_md = PAPER_MD.read_text(encoding="utf-8")
    current_html = (
        PAPER_HTML.read_text(encoding="utf-8") if PAPER_HTML.is_file() else ""
    )
    if args.check:
        if current_md != report or current_html != page:
            print(
                "paper is stale: paper/report.md §5.4 or docs/paper/index.html "
                "no longer matches the ledgers. Run "
                "`python tools/update_paper.py`.",
                file=sys.stderr,
            )
            return 1
        print("paper/report.md and docs/paper/index.html are current.")
        return 0

    changed = []
    if current_md != report:
        PAPER_MD.write_text(report, encoding="utf-8")
        changed.append(str(PAPER_MD.relative_to(REPO)))
    PAPER_HTML.parent.mkdir(parents=True, exist_ok=True)
    if current_html != page:
        PAPER_HTML.write_text(page, encoding="utf-8")
        changed.append(str(PAPER_HTML.relative_to(REPO)))
    print("regenerated: " + (", ".join(changed) if changed else "nothing (current)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
