"""The published paper must match the ledgers it reports.

``paper/report.md``'s §5.4 and its rendered Pages copy
(``docs/paper/index.html``) are generated by ``tools/update_paper.py`` from
the same versioned ledgers the README block uses. This test regenerates both
and fails on any difference, so the paper cannot publish numbers its own
repository no longer supports.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "tools" / "update_paper.py"


def test_paper_and_pages_render_match_the_ledgers() -> None:
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO,
        timeout=120,
    )
    assert result.returncode == 0, (
        f"{result.stdout}{result.stderr}\n"
        "Regenerate with: python tools/update_paper.py"
    )
