"""The Pages landing page must quote the ledgers, not remember them.

The number-bearing regions of ``docs/index.html`` -- the hero SVG card, the
SVG compositor evidence table, and the one-image-every-exporter table -- are
generated by ``tools/update_landing.py`` from the same versioned ledgers as
the README block and the paper. This test regenerates them and fails on any
difference.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "tools" / "update_landing.py"


def test_landing_page_regions_match_the_ledgers() -> None:
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO,
        timeout=120,
    )
    assert result.returncode == 0, (
        f"{result.stdout}{result.stderr}\n"
        "Regenerate with: python tools/update_landing.py"
    )
