"""The live corpus gallery must match its committed assets and the ledgers.

``docs/corpus/index.html`` is generated by ``tools/build_corpus_gallery.py``
from the committed artifact assets plus the cross-checked fidelity ledgers.
This test regenerates it and fails on any difference -- a missing artifact,
a registry edit, or a hand edit to the page.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GENERATOR = REPO / "tools" / "build_corpus_gallery.py"


def test_corpus_gallery_matches_assets_and_ledgers() -> None:
    result = subprocess.run(
        [sys.executable, str(GENERATOR), "--check"],
        capture_output=True,
        text=True,
        cwd=REPO,
        timeout=120,
    )
    assert result.returncode == 0, (
        f"{result.stdout}{result.stderr}\n"
        "Regenerate with: python tools/build_corpus_gallery.py"
    )
